version = 0.1
[default.deploy.parameters]
stack_name = "Todos"
resolve_s3 = true
s3_prefix = "Todos"
region = "cn-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
